package eroc.io.randx.pojo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buffer.proto

public final class Buffer {
  private Buffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface transtionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transtion)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getSaltList();
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    int getSaltCount();
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    com.google.protobuf.ByteString getSalt(int index);

    /**
     * <code>optional bytes dpk = 2;</code>
     */
    boolean hasDpk();
    /**
     * <code>optional bytes dpk = 2;</code>
     */
    com.google.protobuf.ByteString getDpk();

    /**
     * <code>repeated string s = 3;</code>
     */
    java.util.List<String>
        getSList();
    /**
     * <code>repeated string s = 3;</code>
     */
    int getSCount();
    /**
     * <code>repeated string s = 3;</code>
     */
    String getS(int index);
    /**
     * <code>repeated string s = 3;</code>
     */
    com.google.protobuf.ByteString
        getSBytes(int index);

    /**
     * <code>repeated string r = 5;</code>
     */
    java.util.List<String>
        getRList();
    /**
     * <code>repeated string r = 5;</code>
     */
    int getRCount();
    /**
     * <code>repeated string r = 5;</code>
     */
    String getR(int index);
    /**
     * <code>repeated string r = 5;</code>
     */
    com.google.protobuf.ByteString
        getRBytes(int index);

    /**
     * <code>repeated bytes pk = 4;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPkList();
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    int getPkCount();
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    com.google.protobuf.ByteString getPk(int index);

    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    java.util.List<Integer> getLiftcardList();
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    int getLiftcardCount();
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    int getLiftcard(int index);

    /**
     * <pre>
     *牌桌id
     * </pre>
     *
     * <code>optional int32 pid = 7;</code>
     */
    boolean hasPid();
    /**
     * <pre>
     *牌桌id
     * </pre>
     *
     * <code>optional int32 pid = 7;</code>
     */
    int getPid();

    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    boolean hasMsg();
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    String getMsg();
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    boolean hasAction();
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    String getAction();
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();
  }
  /**
   * Protobuf type {@code transtion}
   */
  public  static final class transtion extends
      com.google.protobuf.GeneratedMessageLite<
          transtion, transtion.Builder> implements
      // @@protoc_insertion_point(message_implements:transtion)
      transtionOrBuilder {
    private transtion() {
      salt_ = emptyProtobufList();
      dpk_ = com.google.protobuf.ByteString.EMPTY;
      s_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      r_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      pk_ = emptyProtobufList();
      liftcard_ = emptyIntList();
      msg_ = "";
      action_ = "";
    }
    private int bitField0_;
    public static final int SALT_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> salt_;
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
        getSaltList() {
      return salt_;
    }
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    @Override
    public int getSaltCount() {
      return salt_.size();
    }
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getSalt(int index) {
      return salt_.get(index);
    }
    private void ensureSaltIsMutable() {
      if (!salt_.isModifiable()) {
        salt_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(salt_);
       }
    }
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    private void setSalt(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSaltIsMutable();
      salt_.set(index, value);
    }
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    private void addSalt(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSaltIsMutable();
      salt_.add(value);
    }
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    private void addAllSalt(
        Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureSaltIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, salt_);
    }
    /**
     * <pre>
     *盐
     * </pre>
     *
     * <code>repeated bytes salt = 1;</code>
     */
    private void clearSalt() {
      salt_ = emptyProtobufList();
    }

    public static final int DPK_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString dpk_;
    /**
     * <code>optional bytes dpk = 2;</code>
     */
    @Override
    public boolean hasDpk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes dpk = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getDpk() {
      return dpk_;
    }
    /**
     * <code>optional bytes dpk = 2;</code>
     */
    private void setDpk(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      dpk_ = value;
    }
    /**
     * <code>optional bytes dpk = 2;</code>
     */
    private void clearDpk() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dpk_ = getDefaultInstance().getDpk();
    }

    public static final int S_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<String> s_;
    /**
     * <code>repeated string s = 3;</code>
     */
    @Override
    public java.util.List<String> getSList() {
      return s_;
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    @Override
    public int getSCount() {
      return s_.size();
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    @Override
    public String getS(int index) {
      return s_.get(index);
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getSBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          s_.get(index));
    }
    private void ensureSIsMutable() {
      if (!s_.isModifiable()) {
        s_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(s_);
       }
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    private void setS(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSIsMutable();
      s_.set(index, value);
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    private void addS(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSIsMutable();
      s_.add(value);
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    private void addAllS(
        Iterable<String> values) {
      ensureSIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, s_);
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    private void clearS() {
      s_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string s = 3;</code>
     */
    private void addSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSIsMutable();
      s_.add(value.toStringUtf8());
    }

    public static final int R_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<String> r_;
    /**
     * <code>repeated string r = 5;</code>
     */
    @Override
    public java.util.List<String> getRList() {
      return r_;
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    @Override
    public int getRCount() {
      return r_.size();
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    @Override
    public String getR(int index) {
      return r_.get(index);
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getRBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          r_.get(index));
    }
    private void ensureRIsMutable() {
      if (!r_.isModifiable()) {
        r_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(r_);
       }
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    private void setR(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRIsMutable();
      r_.set(index, value);
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    private void addR(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRIsMutable();
      r_.add(value);
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    private void addAllR(
        Iterable<String> values) {
      ensureRIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, r_);
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    private void clearR() {
      r_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string r = 5;</code>
     */
    private void addRBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRIsMutable();
      r_.add(value.toStringUtf8());
    }

    public static final int PK_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> pk_;
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
        getPkList() {
      return pk_;
    }
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    @Override
    public int getPkCount() {
      return pk_.size();
    }
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString getPk(int index) {
      return pk_.get(index);
    }
    private void ensurePkIsMutable() {
      if (!pk_.isModifiable()) {
        pk_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(pk_);
       }
    }
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    private void setPk(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePkIsMutable();
      pk_.set(index, value);
    }
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    private void addPk(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePkIsMutable();
      pk_.add(value);
    }
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    private void addAllPk(
        Iterable<? extends com.google.protobuf.ByteString> values) {
      ensurePkIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, pk_);
    }
    /**
     * <code>repeated bytes pk = 4;</code>
     */
    private void clearPk() {
      pk_ = emptyProtobufList();
    }

    public static final int LIFTCARD_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.IntList liftcard_;
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    @Override
    public java.util.List<Integer>
        getLiftcardList() {
      return liftcard_;
    }
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    @Override
    public int getLiftcardCount() {
      return liftcard_.size();
    }
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    @Override
    public int getLiftcard(int index) {
      return liftcard_.getInt(index);
    }
    private void ensureLiftcardIsMutable() {
      if (!liftcard_.isModifiable()) {
        liftcard_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(liftcard_);
       }
    }
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    private void setLiftcard(
        int index, int value) {
      ensureLiftcardIsMutable();
      liftcard_.setInt(index, value);
    }
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    private void addLiftcard(int value) {
      ensureLiftcardIsMutable();
      liftcard_.addInt(value);
    }
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    private void addAllLiftcard(
        Iterable<? extends Integer> values) {
      ensureLiftcardIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, liftcard_);
    }
    /**
     * <pre>
     *剩余牌
     * </pre>
     *
     * <code>repeated int32 liftcard = 6;</code>
     */
    private void clearLiftcard() {
      liftcard_ = emptyIntList();
    }

    public static final int PID_FIELD_NUMBER = 7;
    private int pid_;
    /**
     * <pre>
     *牌桌id
     * </pre>
     *
     * <code>optional int32 pid = 7;</code>
     */
    @Override
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *牌桌id
     * </pre>
     *
     * <code>optional int32 pid = 7;</code>
     */
    @Override
    public int getPid() {
      return pid_;
    }
    /**
     * <pre>
     *牌桌id
     * </pre>
     *
     * <code>optional int32 pid = 7;</code>
     */
    private void setPid(int value) {
      bitField0_ |= 0x00000002;
      pid_ = value;
    }
    /**
     * <pre>
     *牌桌id
     * </pre>
     *
     * <code>optional int32 pid = 7;</code>
     */
    private void clearPid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pid_ = 0;
    }

    public static final int MSG_FIELD_NUMBER = 8;
    private String msg_;
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    @Override
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    @Override
    public String getMsg() {
      return msg_;
    }
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msg_);
    }
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    private void setMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      msg_ = value;
    }
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    private void clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000004);
      msg_ = getDefaultInstance().getMsg();
    }
    /**
     * <pre>
     *信息
     * </pre>
     *
     * <code>optional string msg = 8;</code>
     */
    private void setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      msg_ = value.toStringUtf8();
    }

    public static final int ACTION_FIELD_NUMBER = 9;
    private String action_;
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    @Override
    public boolean hasAction() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    @Override
    public String getAction() {
      return action_;
    }
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(action_);
    }
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    private void setAction(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      action_ = value;
    }
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    private void clearAction() {
      bitField0_ = (bitField0_ & ~0x00000008);
      action_ = getDefaultInstance().getAction();
    }
    /**
     * <pre>
     *动作：opengame drawcard drawleftcard returncards
     * </pre>
     *
     * <code>optional string action = 9;</code>
     */
    private void setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      action_ = value.toStringUtf8();
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < salt_.size(); i++) {
        output.writeBytes(1, salt_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, dpk_);
      }
      for (int i = 0; i < s_.size(); i++) {
        output.writeString(3, s_.get(i));
      }
      for (int i = 0; i < pk_.size(); i++) {
        output.writeBytes(4, pk_.get(i));
      }
      for (int i = 0; i < r_.size(); i++) {
        output.writeString(5, r_.get(i));
      }
      for (int i = 0; i < liftcard_.size(); i++) {
        output.writeInt32(6, liftcard_.getInt(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(7, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(8, getMsg());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(9, getAction());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < salt_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(salt_.get(i));
        }
        size += dataSize;
        size += 1 * getSaltList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, dpk_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < s_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(s_.get(i));
        }
        size += dataSize;
        size += 1 * getSList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pk_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(pk_.get(i));
        }
        size += dataSize;
        size += 1 * getPkList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < r_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(r_.get(i));
        }
        size += dataSize;
        size += 1 * getRList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < liftcard_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(liftcard_.getInt(i));
        }
        size += dataSize;
        size += 1 * getLiftcardList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getMsg());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getAction());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static transtion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static transtion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static transtion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static transtion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static transtion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static transtion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static transtion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static transtion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static transtion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static transtion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static transtion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static transtion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(transtion prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code transtion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          transtion, Builder> implements
        // @@protoc_insertion_point(builder_implements:transtion)
        transtionOrBuilder {
      // Construct using Buffer.transtion.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      @Override
      public java.util.List<com.google.protobuf.ByteString>
          getSaltList() {
        return java.util.Collections.unmodifiableList(
            instance.getSaltList());
      }
      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      @Override
      public int getSaltCount() {
        return instance.getSaltCount();
      }
      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getSalt(int index) {
        return instance.getSalt(index);
      }
      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      public Builder setSalt(
          int index, com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSalt(index, value);
        return this;
      }
      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      public Builder addSalt(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addSalt(value);
        return this;
      }
      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      public Builder addAllSalt(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        copyOnWrite();
        instance.addAllSalt(values);
        return this;
      }
      /**
       * <pre>
       *盐
       * </pre>
       *
       * <code>repeated bytes salt = 1;</code>
       */
      public Builder clearSalt() {
        copyOnWrite();
        instance.clearSalt();
        return this;
      }

      /**
       * <code>optional bytes dpk = 2;</code>
       */
      @Override
      public boolean hasDpk() {
        return instance.hasDpk();
      }
      /**
       * <code>optional bytes dpk = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getDpk() {
        return instance.getDpk();
      }
      /**
       * <code>optional bytes dpk = 2;</code>
       */
      public Builder setDpk(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDpk(value);
        return this;
      }
      /**
       * <code>optional bytes dpk = 2;</code>
       */
      public Builder clearDpk() {
        copyOnWrite();
        instance.clearDpk();
        return this;
      }

      /**
       * <code>repeated string s = 3;</code>
       */
      @Override
      public java.util.List<String>
          getSList() {
        return java.util.Collections.unmodifiableList(
            instance.getSList());
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      @Override
      public int getSCount() {
        return instance.getSCount();
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      @Override
      public String getS(int index) {
        return instance.getS(index);
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getSBytes(int index) {
        return instance.getSBytes(index);
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      public Builder setS(
          int index, String value) {
        copyOnWrite();
        instance.setS(index, value);
        return this;
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      public Builder addS(
          String value) {
        copyOnWrite();
        instance.addS(value);
        return this;
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      public Builder addAllS(
          Iterable<String> values) {
        copyOnWrite();
        instance.addAllS(values);
        return this;
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      public Builder clearS() {
        copyOnWrite();
        instance.clearS();
        return this;
      }
      /**
       * <code>repeated string s = 3;</code>
       */
      public Builder addSBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addSBytes(value);
        return this;
      }

      /**
       * <code>repeated string r = 5;</code>
       */
      @Override
      public java.util.List<String>
          getRList() {
        return java.util.Collections.unmodifiableList(
            instance.getRList());
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      @Override
      public int getRCount() {
        return instance.getRCount();
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      @Override
      public String getR(int index) {
        return instance.getR(index);
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getRBytes(int index) {
        return instance.getRBytes(index);
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      public Builder setR(
          int index, String value) {
        copyOnWrite();
        instance.setR(index, value);
        return this;
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      public Builder addR(
          String value) {
        copyOnWrite();
        instance.addR(value);
        return this;
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      public Builder addAllR(
          Iterable<String> values) {
        copyOnWrite();
        instance.addAllR(values);
        return this;
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      public Builder clearR() {
        copyOnWrite();
        instance.clearR();
        return this;
      }
      /**
       * <code>repeated string r = 5;</code>
       */
      public Builder addRBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addRBytes(value);
        return this;
      }

      /**
       * <code>repeated bytes pk = 4;</code>
       */
      @Override
      public java.util.List<com.google.protobuf.ByteString>
          getPkList() {
        return java.util.Collections.unmodifiableList(
            instance.getPkList());
      }
      /**
       * <code>repeated bytes pk = 4;</code>
       */
      @Override
      public int getPkCount() {
        return instance.getPkCount();
      }
      /**
       * <code>repeated bytes pk = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString getPk(int index) {
        return instance.getPk(index);
      }
      /**
       * <code>repeated bytes pk = 4;</code>
       */
      public Builder setPk(
          int index, com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPk(index, value);
        return this;
      }
      /**
       * <code>repeated bytes pk = 4;</code>
       */
      public Builder addPk(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addPk(value);
        return this;
      }
      /**
       * <code>repeated bytes pk = 4;</code>
       */
      public Builder addAllPk(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        copyOnWrite();
        instance.addAllPk(values);
        return this;
      }
      /**
       * <code>repeated bytes pk = 4;</code>
       */
      public Builder clearPk() {
        copyOnWrite();
        instance.clearPk();
        return this;
      }

      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      @Override
      public java.util.List<Integer>
          getLiftcardList() {
        return java.util.Collections.unmodifiableList(
            instance.getLiftcardList());
      }
      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      @Override
      public int getLiftcardCount() {
        return instance.getLiftcardCount();
      }
      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      @Override
      public int getLiftcard(int index) {
        return instance.getLiftcard(index);
      }
      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      public Builder setLiftcard(
          int index, int value) {
        copyOnWrite();
        instance.setLiftcard(index, value);
        return this;
      }
      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      public Builder addLiftcard(int value) {
        copyOnWrite();
        instance.addLiftcard(value);
        return this;
      }
      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      public Builder addAllLiftcard(
          Iterable<? extends Integer> values) {
        copyOnWrite();
        instance.addAllLiftcard(values);
        return this;
      }
      /**
       * <pre>
       *剩余牌
       * </pre>
       *
       * <code>repeated int32 liftcard = 6;</code>
       */
      public Builder clearLiftcard() {
        copyOnWrite();
        instance.clearLiftcard();
        return this;
      }

      /**
       * <pre>
       *牌桌id
       * </pre>
       *
       * <code>optional int32 pid = 7;</code>
       */
      @Override
      public boolean hasPid() {
        return instance.hasPid();
      }
      /**
       * <pre>
       *牌桌id
       * </pre>
       *
       * <code>optional int32 pid = 7;</code>
       */
      @Override
      public int getPid() {
        return instance.getPid();
      }
      /**
       * <pre>
       *牌桌id
       * </pre>
       *
       * <code>optional int32 pid = 7;</code>
       */
      public Builder setPid(int value) {
        copyOnWrite();
        instance.setPid(value);
        return this;
      }
      /**
       * <pre>
       *牌桌id
       * </pre>
       *
       * <code>optional int32 pid = 7;</code>
       */
      public Builder clearPid() {
        copyOnWrite();
        instance.clearPid();
        return this;
      }

      /**
       * <pre>
       *信息
       * </pre>
       *
       * <code>optional string msg = 8;</code>
       */
      @Override
      public boolean hasMsg() {
        return instance.hasMsg();
      }
      /**
       * <pre>
       *信息
       * </pre>
       *
       * <code>optional string msg = 8;</code>
       */
      @Override
      public String getMsg() {
        return instance.getMsg();
      }
      /**
       * <pre>
       *信息
       * </pre>
       *
       * <code>optional string msg = 8;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getMsgBytes() {
        return instance.getMsgBytes();
      }
      /**
       * <pre>
       *信息
       * </pre>
       *
       * <code>optional string msg = 8;</code>
       */
      public Builder setMsg(
          String value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <pre>
       *信息
       * </pre>
       *
       * <code>optional string msg = 8;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }
      /**
       * <pre>
       *信息
       * </pre>
       *
       * <code>optional string msg = 8;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgBytes(value);
        return this;
      }

      /**
       * <pre>
       *动作：opengame drawcard drawleftcard returncards
       * </pre>
       *
       * <code>optional string action = 9;</code>
       */
      @Override
      public boolean hasAction() {
        return instance.hasAction();
      }
      /**
       * <pre>
       *动作：opengame drawcard drawleftcard returncards
       * </pre>
       *
       * <code>optional string action = 9;</code>
       */
      @Override
      public String getAction() {
        return instance.getAction();
      }
      /**
       * <pre>
       *动作：opengame drawcard drawleftcard returncards
       * </pre>
       *
       * <code>optional string action = 9;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getActionBytes() {
        return instance.getActionBytes();
      }
      /**
       * <pre>
       *动作：opengame drawcard drawleftcard returncards
       * </pre>
       *
       * <code>optional string action = 9;</code>
       */
      public Builder setAction(
          String value) {
        copyOnWrite();
        instance.setAction(value);
        return this;
      }
      /**
       * <pre>
       *动作：opengame drawcard drawleftcard returncards
       * </pre>
       *
       * <code>optional string action = 9;</code>
       */
      public Builder clearAction() {
        copyOnWrite();
        instance.clearAction();
        return this;
      }
      /**
       * <pre>
       *动作：opengame drawcard drawleftcard returncards
       * </pre>
       *
       * <code>optional string action = 9;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setActionBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:transtion)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new transtion();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          salt_.makeImmutable();
          s_.makeImmutable();
          r_.makeImmutable();
          pk_.makeImmutable();
          liftcard_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          transtion other = (transtion) arg1;
          salt_= visitor.visitList(salt_, other.salt_);
          dpk_ = visitor.visitByteString(
              hasDpk(), dpk_,
              other.hasDpk(), other.dpk_);
          s_= visitor.visitList(s_, other.s_);
          r_= visitor.visitList(r_, other.r_);
          pk_= visitor.visitList(pk_, other.pk_);
          liftcard_= visitor.visitIntList(liftcard_, other.liftcard_);
          pid_ = visitor.visitInt(
              hasPid(), pid_,
              other.hasPid(), other.pid_);
          msg_ = visitor.visitString(
              hasMsg(), msg_,
              other.hasMsg(), other.msg_);
          action_ = visitor.visitString(
              hasAction(), action_,
              other.hasAction(), other.action_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  if (!salt_.isModifiable()) {
                    salt_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(salt_);
                  }
                  salt_.add(input.readBytes());
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000001;
                  dpk_ = input.readBytes();
                  break;
                }
                case 26: {
                  String s = input.readString();
                  if (!s_.isModifiable()) {
                    s_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(s_);
                  }
                  s_.add(s);
                  break;
                }
                case 34: {
                  if (!pk_.isModifiable()) {
                    pk_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(pk_);
                  }
                  pk_.add(input.readBytes());
                  break;
                }
                case 42: {
                  String s = input.readString();
                  if (!r_.isModifiable()) {
                    r_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(r_);
                  }
                  r_.add(s);
                  break;
                }
                case 48: {
                  if (!liftcard_.isModifiable()) {
                    liftcard_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(liftcard_);
                  }
                  liftcard_.addInt(input.readInt32());
                  break;
                }
                case 50: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!liftcard_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    liftcard_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(liftcard_);
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    liftcard_.addInt(input.readInt32());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 56: {
                  bitField0_ |= 0x00000002;
                  pid_ = input.readInt32();
                  break;
                }
                case 66: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  msg_ = s;
                  break;
                }
                case 74: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  action_ = s;
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<transtion> parser = PARSER;
          if (parser == null) {
            synchronized (transtion.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:transtion)
    private static final transtion DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new transtion();
    }

    public static transtion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<transtion> PARSER;

    public static com.google.protobuf.Parser<transtion> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
